<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyVersion>1.0.1.1</AssemblyVersion>
    <FileVersion>1.0.1.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="drewCo.Tools" Version="1.5.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="test-data\ExampleCommand1.toml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
